language: go
go:
- '1.13'
install:
- go mod tidy
- go build -v ./...
before_deploy:
- mkdir -p releases/linux
- mkdir -p releases/darwin
- GOOS=linux GOARCH=amd64 go build -o releases/linux/mapr github.com/rcaught/mapr
- GOOS=darwin GOARCH=amd64 go build -o releases/darwin/mapr github.com/rcaught/mapr
- cd releases/linux
- chmod +x mapr
- zip linux.zip mapr
- cd ../darwin
- chmod +x mapr
- zip macos.zip mapr
- cd ../..
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: j6cv3QFUTQsUD3B6RFOZfEg3hHb218Splln2LVsfPEzO94qCAJQyMOHkPU1s1vGNoumOePhqVXw2beVrWK6/5Bz/51M60+kFkS7dKMrtB4XprMcon3OHmwUscmwoxQMqn6Pj6eub2ku7jWzvc2YR6xXB/ALQ3Bkap8GCQY3+KKC6U1aitrfEmi3f9EH3UFMaljfDFjYITsFoRmbBcy96wFFgwNm7nsMsapDV+eeelXZPx0UMVznsoF0dPEofux5s+9IXKmYbTP1PTCwLf13vqmwHu8hX+C0ZgTuQlh/Rk/cFrOh30+o+RhYMuPSKSUFpeo/QqnenJY3s3WdHT2n7lnIDijQFJ4hVVR/2ya0DAsUnMnDZjIHsbP4n7vrClVa4azzj00ye5JeTDCpDi4WEaUD+ddOaMknFxi7VOEMdNj81utAx/O4UPijqpw+l+ikXL86zZcEpWVQf9z9QL2pAXv4gPXzz2vNHeE85cGl6C1I4/NackFSqL7aILWUvzoDHof8jKdCDF7Rkzvv0bzWnSdHN/m7gkMXKIHFpfb4rLwpSsQrp4RvvGyLU5CcXn/OB6IPL8bZb0Ayx/Aq6ou0V4Uw30jEM/w4WMYMg0m7U4Ufsczh0iRU81PwhNNgXjOayYUDIKScb7ZgPCKDvgSXc1cHmydgTJvPNCLdLFUSW1/4=
  file:
  - releases/linux/linux.zip
  - releases/darwin/macos.zip
  on:
    repo: rcaught/mapr
    tags: true
